config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy] do
      put :toggle
    end
  end

  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :to_dos
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Devise looks for this method automatically, don't need to call anywhere
  def  after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = current_user.items.build(item_params)

    if @item.save!
      flash[:notice] = "Item was saved"
    else
      flash[:error] = "There was a problem saving your item"
    end
    #redirect_to user_path(current_user)

    respond_to do |format|
      format.html
      format.js
    end

  end

  def destroy
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "Item was completed"
    else
      flash[:error] = "There was a problem deleting your item"
    end
    #redirect_to user_path(current_user)

    respond_to do |format|
      format.html
      format.js
    end
  end

 
  def toggle
    @item = Item.find(params[:item_id])
    if @item.complete
      @item.complete = false
    elsif @item.complete == false
      @item.complete = true
    elsif @item.complete == nil
      @item.complete = true
    end
    @item.save
    redirect_to user_path(@item.user)
  end

  private 

  def item_params
    params.require(:item).permit(:name, :complete)
  end

end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  def new
  end

  def delete
  end

  def create
  end

  def edit
  end

  def toggle
    @to_do = ToDo.find(params[:to_do_id])
    if @to_do.resolved
      @to_do.resolved = false
    else
      @to_do.resolved = true
    end
    @to_do.save
    redirect_to user_path(@to_do.user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user == nil
      redirect_to welcome_index_path
    else
      @user = User.find(params[:id])
      @items = @user.items
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [current_user, Item.new], remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter task here!" %>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<%= content_tag :li, id: "item-#{item.id}" do %>
  <%= item.name %>
  <%= item.days_left%> days left!
  <%= link_to "delete", [current_user, item], method: :delete, class: "glyphicon glyphicon-ok", remote: true %>
<% end %>

app/views/items/create.js.erb
$('#js-items').append("<%= escape_javascript(render(@item)) %>");

app/views/items/destroy.js.erb
 <% if @item.destroyed? %>
   $('#item-' +<%= @item.id %>).hide();

 <% else %>
   $('#item-' +<%= @item.id %>).append("<div class='alert alert-danger'><%= flash[:error] %></div>");
 <% end %>

app/views/items/stupid.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/toggle.html.erb
<h1>Items#toggle</h1>
<p>Find me in app/views/items/toggle.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "BlocItOff", root_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
  
      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= link_to (current_user.name || current_user.email), current_user %>! 
          <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do%>
            <span class="glyphicon glyphicon-user"></span>
          <% end %> 
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-log-out"></span>
          <% end %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/to_dos/delete.html.erb
<h1>ToDos#delete</h1>
<p>Find me in app/views/to_dos/delete.html.erb</p>

app/views/to_dos/edit.html.erb
<h1>ToDos#edit</h1>
<p>Find me in app/views/to_dos/edit.html.erb</p>

app/views/to_dos/new.html.erb
<h1>ToDos#new</h1>
<p>Find me in app/views/to_dos/new.html.erb</p>

app/views/users/show.html.erb
<div class="media">
  <div class="col-md-8">
    <div class="media-body">
      <h2 class="media-heading"><%= current_user.name || current_user.email %>'s To Do List</h2>
      <ul class="list-unstyled" id="js-items">
        <%= render @items %>
      </ul>
      <%= render partial: "items/form", locals: {user: @user} %>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to BlocItOff!</h1>
<p>This is the homepage for bloccitoff</p>